map $http_x_forwarded_proto $pdc_forwarded_proto {
    default $http_x_forwarded_proto;
    "" $scheme;
}

map $http_x_forwarded_port $pdc_forwarded_port {
    default $http_x_forwarded_port;
    "" $server_port;
}

server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://backend:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $pdc_forwarded_proto;
        proxy_set_header X-Forwarded-Port $pdc_forwarded_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api-docs {
        proxy_pass http://backend:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $pdc_forwarded_proto;
        proxy_set_header X-Forwarded-Port $pdc_forwarded_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api-docs-json {
        proxy_pass http://backend:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $pdc_forwarded_proto;
        proxy_set_header X-Forwarded-Port $pdc_forwarded_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /health {
        proxy_pass http://backend:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $pdc_forwarded_proto;
        proxy_set_header X-Forwarded-Port $pdc_forwarded_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    location /auth/ {
        proxy_pass http://keycloak:8080;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $pdc_forwarded_proto;
        proxy_set_header X-Forwarded-Port $pdc_forwarded_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }


    location / {
        try_files $uri $uri/ /index.html;
    }
}
